### PR TITLE
Pin a minimum version for each notebook (0.7.2 default)

### PR DESCRIPTION
**Pull request by MarkDaoust**

### CODE REVIEW

**Comment by random-forests** [comment]
Thanks for this. Hmm, question -- 

In colab, the version currently installed by default is 0.7.2.

```
import google.generativeai
google.generativeai.__version__

0.7.2
```

But running

`!pip install -qU \"google-generativeai>=0.7.2`

still causes colab to uninstall and reinstall the package. Is that just me? (Is there a way we can get a minimum version pinned for some notebooks that doesn't cause that, just so they run faster?) Thanks!

**Comment by MarkDaoust** [comment]
I'm updating Colab to use 0.8.0 in cl/673024762.

**Comment by random-forests** [comment]
Nice!

**Review by random-forests — APPROVED** [review]

**Comment by Alexisloyolamend3z** [comment]
Hola amigos

**Pull request merged**
