### PR TITLE
Fix: Convert BGR to RGB color space for correct video colors

### PR DESCRIPTION
**Pull request by robotlovehuman**
# Video Feed Color Correction

## Issue
- Video feed shows blue tint due to BGR/RGB colorspace mismatch between OpenCV and PIL
- OpenCV captures in BGR format while PIL expects RGB

## Fix
- Added cv2.cvtColor conversion before PIL processing
- Converts OpenCV's BGR output to RGB before PIL processing
- Added explanatory comments for future maintainers

## Testing
- Tested with live video feed
- Confirms correct color reproduction without blue tint
- No impact on performance or other functionality

## Technical Details
- Modified _get_frame method to include color space conversion
- Uses cv2.COLOR_BGR2RGB for correct color mapping
- Maintains existing image processing pipeline

### CODE REVIEW

**Review by markmcd — APPROVED** [review]
Fantastic - thanks for the fix!

**Comment by robotlovehuman** [comment]
Wow this is my first contribution ever! I am a Youtuber who learnt coding entirely from Gemini I made into a cool quirky coding professor and I've learning from it for about a year now! And learnt flutter and now creating a really cool app! I am a filmmaker and a musician from Egypt, and I would love to like just show you guys the amazing crazy stuff I built that combines my unique Egyptian Arabic background with all your a.i tools!

PS: thanks again for approving my fix!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MarkDaoust** [comment]
Thanks @robotlovehuman.

**Pull request merged**
