### PR TITLE
langchain and gemini

### PR DESCRIPTION
**Pull request by hemanth**
Example of using langchain with gemini.

### CODE REVIEW

**Comment by markmcd** [comment]
Hey @hemanth - thanks for the contribution & sorry for the super slow response!

Could you give me an outline of what you want this guide to achieve? Just a high level sentence or two. I want to make sure it's not already covered by our existing [Langchain content](https://github.com/google-gemini/cookbook/tree/main/examples/langchain).

**Comment by hemanth** [comment]
@markmcd NP! Back then in may there was no [Langchain content](https://github.com/google-gemini/cookbook/tree/main/examples/langchain).

This PR demonstrates how to use the Langchain framework with Google's Gemini Pro language model. It showcases various Langchain features, such as prompt templates, chains, agents, and memory, using code examples to interact with Gemini Pro for tasks like generating creative text formats, answering questions, and executing code 🤓

**Comment by markmcd** [comment]
> This PR demonstrates how to use the Langchain framework with Google's Gemini Pro language model. It showcases various Langchain features, such as prompt templates, chains, agents, and memory, using code examples to interact with Gemini Pro for tasks like generating creative text formats, answering questions, and executing code 🤓

OK sounds good - can you make sure the guide has some text in it? I've started a template in #263 that includes some general advice, but basically include some detail about what the reader can expect to learn, and then explain it as you go through. This will help make it useful to more people, and will help us with ongoing maintenance.

We typically keep the notebooks focused on a single task too (e.g. "building an agent with gemini and LC") so if this starts to get big, you might want to to split it up.

And at some point you'll need to rebase onto the latest `main` too, so the notebook format/link checks are run.

> Back then in may there was no Langchain content.

Before we had the cookbook we used [the docs repo](https://github.com/google/generative-ai-docs/tree/b91b55fd62c54817e6361ff29111bc6485fffec4/examples/gemini/python/langchain), so there was a gap where it appeared here that we didn't have some integrations. No problem though.

**Comment by hemanth** [comment]
> can you make sure the guide has some text in it?

Sure, I can add that.

> you might want to to split it up.
will check and spilt it into smaller notebooks

> notebook format/link checks are run.
got it.

> [the docs repo](https://github.com/google/generative-ai-docs/tree/b91b55fd62c54817e6361ff29111bc6485fffec4/examples/gemini/python/langchain),

Ah! Yes, I remember seeing these.

**Pull request closed without merging**
