### PR TITLE
LlamaIndex and Gemini Quickstart

### PR DESCRIPTION
**Pull request by lucifertrj**
This PR contains a notebook: where anyone can get started with LlamaIndex with Gemini as the LLM. 
- Approach-1: Using Image URL as input
- Approach-2: Using local image

### CODE REVIEW

**Comment by MarkDaoust** [comment]
Manually confirmed CLA. All good there.

**Comment by lucifertrj** [comment]
> Manually confirmed CLA. All good there.

Hi @MarkDaoust 

Thank you for the confirmation. The review hasn't been reviewed to merge

**Comment by TYMichaelChen** [comment]
Am I doing something wrong here? I get an error: `ModuleNotFoundError: No module named 'llama_index.multi_modal_llms.generic_utils'`
image

**Review by MarkDaoust — CHANGES_REQUESTED** [review]
We need images that are clearly open-licensed. We can't merge it with these images.

**Comment by lucifertrj** [comment]
> We need images that are clearly open-licensed. We can't merge it with these images.

Sure, understood, will modify it

**Comment by lucifertrj** [comment]
> Am I doing something wrong here? I get an error: `ModuleNotFoundError: No module named 'llama_index.multi_modal_llms.generic_utils'` image

LlamaIndex version is changed, we need to install this:

```bash
!pip install llama-index-multi-modal-llms-gemini
```

I will update the notebook, with free open licensed images and updated modules to run the Quickstart guide

**Comment by lucifertrj** [comment]
@TYMichaelChen 

Few changes to note:

- SimpleDirectoryReader is now imported via `llama_index.core`
- `from llama_index.multi_modal_llms.generic_utils import load_image_urls` is now called via llama_index.core i.e., `from llama_index.core.multi_modal_llms.generic_utils import load_image_urls`

@MarkDaoust 

Used Open Licenses images from Unsplash

**Review by MarkDaoust — CHANGES_REQUESTED** [review]
Please delete the ".DS_Store" file.

For external integrations we're going to start an /examples/integrations directory. Can you create the directory and move this from /quickstarts/ to examples/integrations?

Thanks.

**Comment by lucifertrj** [comment]
> Please delete the ".DS_Store" file.
> 
> For external integrations we're going to start an /examples/integrations directory. Can you create the directory and move this from /quickstarts/ to examples/integrations?
> 
> Thanks.

Done

**Comment by markmcd** [comment]
Hey @lucifertrj - sorry it's taken a while to get to this. Thanks for the contribution.

Can you give us a bit of context as to what this guide is trying to achieve? Right now it's missing some key introductory text to explain to the user what they are going to learn & do. For my context, and for the guide, can you give it a high level description, like "How to use Llama Index with the Gemini API for multi-turn chat conversations" or whatever task you want cover.

Before we review the content in detail it'd be great to make sure that this doesn't duplicate any existing content, and has some value on its own, so this info will help.

**Pull request closed without merging**
