### PR TITLE
add litellm example (OpenAI-Compatible Endpoint)

### PR DESCRIPTION
**Pull request by krrishdholakia**
Hi @random-forests @markmcd,

Adding a tutorial to show how to call Gemini through an OpenAI-Compatible Endpoint (via [LiteLLM](https://github.com/BerriAI/litellm))

This supports Google AI Studio + Vertex AI as well. 

Let me know if there's anything further required here!

### CODE REVIEW

**Comment by MarkDaoust** [comment]
Hi, we're planning to put integration examples like this in an examples/integrations/ directory. Can you create that directory and move this file into it?

**Comment by MarkDaoust** [comment]
Also, se can't merge anything until you sign the CLA.

**Comment by krrishdholakia** [comment]
Hey @MarkDaoust thanks for the bump - just signed the CLA

**Comment by markmcd** [comment]
Please ignore the "stale" check above.  I'll reset the counter since you were waiting on us.

I've rebased your PR to the current head to pick up the lint, etc checks. Please take a look at them.

Can you also:
* Give the guide a descriptive title - it needs to describe what this guide demonstrates (include the task, like "question answering" or "building a chatbot" -  it could be something like "Generating content with LiteLLM" or "Issuing OpenAI compatible requests to the Gemini API with LiteLLM")
* Update the filename to match, and put it in `examples/litellm/...`
* Add an intro sentence/paragraph to explain what task the reader is going to implement, including links to relevant content (like litellm docs).
*  Also add descriptions to each section of the guide, explaining what will be done.
* Include response outputs where they are helpful, e.g. to show the model has responsed.

For a good example, check out [this langchain example](https://github.com/google-gemini/cookbook/blob/main/examples/langchain/Gemini_LangChain_QA_Pinecone_WebLoad.ipynb) (but yours can be much shorter).

Also please refer to the [style guide](https://developers.google.com/style/) for guidance on how to structure your text.

**Pull request closed without merging**
