### PR TITLE
Update Story_Writing_with_Prompt_Chaining.ipynb

### PR DESCRIPTION
**Pull request by younesbram**
typo fix

### CODE REVIEW

**Review by MarkDaoust — APPROVED** [review]

**Comment by MarkDaoust** [comment]
Hi, please sign the CLA so we can merge this. Thanks!

**Comment by younesbram** [comment]
> Hi, please sign the CLA so we can merge this. Thanks!

Done. Thank you sir

**Review by MarkDaoust — APPROVED** [review]

**Comment by younesbram** [comment]
Hello Sir Daoust.I think I already have? Is there a mistake?Younes BrahimiSent from my iPhoneOn Jun 4, 2024, at 12:06 PM, Mark Daoust ***@***.***> wrote:﻿
@MarkDaoust approved this pull request.

**Review by MarkDaoust — APPROVED** [review]

**Comment by MarkDaoust** [comment]
Yeah, it just needed a refresh. Thanks!

**Comment by younesbram** [comment]
Thank you for the promptness, sir. I realize its a small typo and not a big
contribution but I will keep my eyes on anything better I can contribute,
thank you for keeping this repo alive

Younes Brahimi

**Pull request merged**
